### ISSUE TITLE
Setup CI to automagically build master from source

### ISSUE THREAD

**Issue by bithakr** [triplestrange/triplestrange.github.io#1]
Looks like travis can do this?

**Comment by PenguinSnail** [comment]
[https://gist.github.com/domenic/ec8b0fc8ab45f39403dd](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd)
[https://docs.travis-ci.com/user/deployment/pages/](https://docs.travis-ci.com/user/deployment/pages/)
These two have good examples on making travis do this. Should be able to set it up with an SSH key for the organization instead of a personal one

**Comment by PenguinSnail** [comment]
Commits to `hugo-source` are now automatically built and published to `master` by Travis CI
